name: tests

on:
  push:
    branches: [ master ]
  pull_request:
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python_version: ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]
    runs-on: ubuntu-latest
    name: ${{ matrix.python_version }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test
      run: tox -e ${{ matrix.python_version }}
